image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8080
  onOpen: open-browser
- port: 8088
  onOpen: open-preview
- port: 6080
  onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'
- command: pip install pylint
- command: PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.7.4
- command: pyenv global 3.7.4
- command: LD_LIBRARY_PATH=/home/.pyenv
